# AAI614: Data Science & its Applications

*Notebook 2.2: Descriptive Statistical Information*

<a href="https://colab.research.google.com/github/harmanani/AAI614/blob/main/Week%202/Notebook2.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import ssl

ssl._create_default_https_context = ssl._create_unverified_context
alcohool = pd.read_csv("https://raw.githubusercontent.com/harmanani/AAI614/main/Week%202/niaaa-report2009.csv", index_col ='State')

In [2]:
alcohool.max()

Beer       1.72
Wine       1.00
Spirits    1.82
dtype: float64

In [3]:
alcohool.min()

Beer       0.70
Wine       0.10
Spirits    0.45
dtype: float64

In [4]:
alcohool['Beer'].median()

np.float64(1.22)

In [5]:
alcohool.median()

Beer       1.22
Wine       0.34
Spirits    0.74
dtype: float64

In [6]:
alcohool['Wine'].std()

np.float64(0.20113852411299268)

In [7]:
alcohool.describe()

            Beer       Wine    Spirits
count  51.000000  51.000000  51.000000
mean    1.239608   0.384118   0.819804
std     0.210200   0.201139   0.266732
min     0.700000   0.100000   0.450000
25%     1.095000   0.225000   0.660000
50%     1.220000   0.340000   0.740000
75%     1.365000   0.520000   0.880000
max     1.720000   1.000000   1.820000

In [8]:
alcohool.idxmax()

Beer              New Hampshire
Wine       District of Columbia
Spirits           New Hampshire
dtype: object

In [9]:
alcohool.loc[:'Hawaii'].cumsum().head()

            Beer  Wine  Spirits
State
Alabama     1.20  0.22     0.58
Alaska      2.51  0.76     1.74
Arizona     3.70  1.14     2.48
Arkansas    4.77  1.31     3.08
California  5.82  1.86     3.81